name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://drive.google.com/uc?id=1XL5WVI9GWOkr8xU5F0j9so_nn6qEfbaB -OutFile start.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1WpuxGMyptg2n0ItKJbh3tKa2UESQzFE_ -OutFile wallpaper.jpg
        Invoke-WebRequest https://drive.google.com/uc?id=16R90dAHpT5mOnqIVmZjMotgODv7AqYRP -OutFile wallpaper.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1t8SnlSQLw2eIkUqT646mZ9Qr9D037-S0 -OutFile loop.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: Berhasil Dibuat! Anda Bisa Menutup Tab Sekarang.
      run: cmd /c loop.bat
